name: lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-typecheck:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Enable Corepack
        run: |
          corepack enable
          yarn set version stable
          
      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Types
        run: yarn typecheck

      - name: Run ESLint
        run: yarn lint
  test:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Enable Corepack
        run: corepack enable
          
      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

